/**
 * fhir-validator — Public Interfaces & Types
 *
 * Defines the core abstractions for the FHIR validator module:
 * - {@link ValidationOptions} — validation configuration
 * - {@link ValidationResult} — validation output
 * - {@link ValidationIssue} — issue reporting
 * - {@link ValidationIssueCode} — machine-readable issue codes
 * - {@link ValidationContext} — internal validation state
 *
 * This module implements structural validation of FHIR resource instances
 * against profile snapshots generated by the fhir-profile module.
 *
 * @module fhir-validator
 */

import type { CanonicalProfile, Resource } from '../model/index.js';

// =============================================================================
// Section 1: Validation Options
// =============================================================================

/**
 * Configuration options for structural validation.
 *
 * @example
 * ```typescript
 * const options: ValidationOptions = {
 *   profileUrl: 'http://hl7.org/fhir/StructureDefinition/Patient',
 *   validateSlicing: true,
 *   validateFixed: true,
 *   failFast: false,
 * };
 * ```
 */
export interface ValidationOptions {
  /**
   * Profile URL to validate against.
   *
   * If not specified, the validator will attempt to extract the profile
   * from `resource.meta.profile[0]`. If neither is available, the
   * validator falls back to the base resource type
   * (e.g., `http://hl7.org/fhir/StructureDefinition/{resourceType}`).
   */
  readonly profileUrl?: string;

  /**
   * Whether to validate slicing constraints.
   *
   * When `true` (default), the validator checks that array elements
   * match their declared slices and that closed slicing rules are
   * respected.
   *
   * @default true
   */
  readonly validateSlicing?: boolean;

  /**
   * Whether to validate fixed and pattern value constraints.
   *
   * When `true` (default), the validator checks that element values
   * match any `fixed[x]` or `pattern[x]` constraints declared in
   * the profile.
   *
   * @default true
   */
  readonly validateFixed?: boolean;

  /**
   * Maximum depth for nested validation.
   *
   * Prevents runaway recursion in deeply nested or pathological
   * resource structures.
   *
   * @default 50
   */
  readonly maxDepth?: number;

  /**
   * Whether to stop on the first error or collect all issues.
   *
   * When `true`, the validator throws a {@link ValidationFailedError}
   * on the first error-severity issue. When `false` (default), all
   * issues are collected and returned in the result.
   *
   * @default false
   */
  readonly failFast?: boolean;
}

// =============================================================================
// Section 2: Validation Result
// =============================================================================

/**
 * Result of structural validation.
 *
 * Contains the overall validity status, the validated resource, and
 * all issues encountered during validation.
 *
 * @example
 * ```typescript
 * const result = await validator.validate(patient);
 * if (result.valid) {
 *   console.log('Resource is valid');
 * } else {
 *   for (const issue of result.issues) {
 *     console.error(`${issue.severity}: ${issue.message} (at ${issue.path})`);
 *   }
 * }
 * ```
 */
export interface ValidationResult {
  /**
   * Whether the resource is valid.
   *
   * `true` when no error-severity issues were recorded.
   * Warnings and informational issues do not affect this flag.
   */
  readonly valid: boolean;

  /** The resource that was validated. */
  readonly resource: Resource;

  /** The profile that was validated against. */
  readonly profileUrl: string;

  /** The resolved CanonicalProfile used for validation. */
  readonly profile: CanonicalProfile;

  /** Issues encountered during validation (errors + warnings + info). */
  readonly issues: readonly ValidationIssue[];
}

// =============================================================================
// Section 3: Validation Issue
// =============================================================================

/**
 * A single issue encountered during validation.
 *
 * Mirrors the concept of FHIR OperationOutcome.issue but scoped to
 * structural validation. Issues are collected during validation and
 * returned in {@link ValidationResult.issues}.
 *
 * @example
 * ```typescript
 * const issue: ValidationIssue = {
 *   severity: 'error',
 *   code: 'CARDINALITY_MIN_VIOLATION',
 *   message: "Element 'Patient.name' requires at least 1 value(s), but found 0",
 *   path: 'Patient.name',
 *   expression: 'Patient.name',
 * };
 * ```
 */
export interface ValidationIssue {
  /** Severity level of the issue. */
  readonly severity: 'error' | 'warning' | 'information';

  /** Machine-readable issue code. */
  readonly code: ValidationIssueCode;

  /** Human-readable description of the issue. */
  readonly message: string;

  /**
   * Element path where the issue occurred (dot-notation).
   *
   * @example `'Patient.name'`, `'Observation.value[x]'`
   */
  readonly path?: string;

  /**
   * FHIRPath expression pointing to the problematic element.
   *
   * Typically identical to `path` for structural validation, but may
   * differ for sliced elements or choice types.
   *
   * @example `'Patient.identifier.where(system="urn:oid:1.2.3")'`
   */
  readonly expression?: string;

  /** Additional diagnostic information for debugging. */
  readonly diagnostics?: string;
}

// =============================================================================
// Section 4: Validation Issue Codes
// =============================================================================

/**
 * Machine-readable issue codes for structural validation.
 *
 * Each code corresponds to a specific category of validation failure.
 * Codes are designed to be stable across versions for programmatic
 * consumption.
 */
export type ValidationIssueCode =
  // ─── Cardinality ───
  /** Element has fewer values than the minimum cardinality. */
  | 'CARDINALITY_MIN_VIOLATION'
  /** Element has more values than the maximum cardinality. */
  | 'CARDINALITY_MAX_VIOLATION'

  // ─── Type ───
  /** Value type does not match any of the allowed types. */
  | 'TYPE_MISMATCH'
  /** Choice type field uses an unsupported type suffix. */
  | 'INVALID_CHOICE_TYPE'

  // ─── Required Elements ───
  /** A required element (min ≥ 1) is missing from the resource. */
  | 'REQUIRED_ELEMENT_MISSING'

  // ─── Fixed / Pattern ───
  /** Value does not match the fixed value constraint. */
  | 'FIXED_VALUE_MISMATCH'
  /** Value does not match the pattern value constraint (partial match). */
  | 'PATTERN_VALUE_MISMATCH'

  // ─── Slicing ───
  /** Value does not match any slice discriminator in a closed slicing. */
  | 'SLICING_NO_MATCH'
  /** Slice cardinality violation (too few or too many values in a slice). */
  | 'SLICING_CARDINALITY_VIOLATION'
  /** Ordered slicing constraint violated (values out of order). */
  | 'SLICING_ORDER_VIOLATION'

  // ─── Reference ───
  /** Reference target does not match any of the allowed target profiles. */
  | 'REFERENCE_TARGET_MISMATCH'

  // ─── Profile ───
  /** The specified profile could not be found or loaded. */
  | 'PROFILE_NOT_FOUND'
  /** Resource type does not match the profile's type. */
  | 'RESOURCE_TYPE_MISMATCH'

  // ─── Unknown ───
  /** Resource contains an element not defined in the profile. */
  | 'UNKNOWN_ELEMENT'

  // ─── Invariant (placeholder for Phase 6) ───
  /** FHIRPath invariant evaluation is not yet supported. */
  | 'INVARIANT_NOT_EVALUATED'

  // ─── Internal ───
  /** Internal validator error (should not happen). */
  | 'INTERNAL_ERROR';

// =============================================================================
// Section 5: Validation Context (Internal)
// =============================================================================

/**
 * Internal state passed through the validation traversal.
 *
 * Tracks the current depth, accumulated issues, and options
 * for the validation run.
 *
 * @internal Used by the StructureValidator and validation rules.
 */
export interface ValidationContext {
  /** The CanonicalProfile being validated against. */
  readonly profile: CanonicalProfile;

  /** Mutable array of accumulated issues. */
  readonly issues: ValidationIssue[];

  /** Resolved validation options. */
  readonly options: Required<ValidationOptions>;

  /** Current traversal depth (for maxDepth enforcement). */
  depth: number;
}

// =============================================================================
// Section 6: Helper Functions
// =============================================================================

/**
 * Create a {@link ValidationIssue} with the given parameters.
 *
 * Convenience factory to reduce boilerplate when recording issues.
 *
 * @param severity - Issue severity level.
 * @param code - Machine-readable issue code.
 * @param message - Human-readable description.
 * @param options - Optional path, expression, and diagnostics.
 * @returns A frozen ValidationIssue object.
 */
export function createValidationIssue(
  severity: ValidationIssue['severity'],
  code: ValidationIssueCode,
  message: string,
  options?: {
    path?: string;
    expression?: string;
    diagnostics?: string;
  },
): ValidationIssue {
  const issue: ValidationIssue = { severity, code, message };
  if (options?.path !== undefined) {
    (issue as { path: string }).path = options.path;
  }
  if (options?.expression !== undefined) {
    (issue as { expression: string }).expression = options.expression;
  }
  if (options?.diagnostics !== undefined) {
    (issue as { diagnostics: string }).diagnostics = options.diagnostics;
  }
  return issue;
}

/**
 * Create a {@link ValidationContext} with resolved defaults.
 *
 * @param profile - The CanonicalProfile to validate against.
 * @param options - User-provided options (defaults applied for missing fields).
 * @returns A new ValidationContext ready for traversal.
 *
 * @internal
 */
export function createValidationContext(
  profile: CanonicalProfile,
  options?: ValidationOptions,
): ValidationContext {
  return {
    profile,
    issues: [],
    options: {
      profileUrl: options?.profileUrl ?? profile.url,
      validateSlicing: options?.validateSlicing ?? true,
      validateFixed: options?.validateFixed ?? true,
      maxDepth: options?.maxDepth ?? 50,
      failFast: options?.failFast ?? false,
    },
    depth: 0,
  };
}

/**
 * Resolve default validation options.
 *
 * Fills in missing fields with sensible defaults.
 *
 * @param options - User-provided options (may be partial).
 * @returns Fully resolved options with all fields populated.
 */
export function resolveValidationOptions(
  options?: ValidationOptions,
): Required<ValidationOptions> {
  return {
    profileUrl: options?.profileUrl ?? '',
    validateSlicing: options?.validateSlicing ?? true,
    validateFixed: options?.validateFixed ?? true,
    maxDepth: options?.maxDepth ?? 50,
    failFast: options?.failFast ?? false,
  };
}

/**
 * Check whether a validation result has any error-severity issues.
 *
 * @param issues - The issues to check.
 * @returns `true` if any issue has severity `'error'`.
 */
export function hasValidationErrors(
  issues: readonly ValidationIssue[],
): boolean {
  return issues.some((i) => i.severity === 'error');
}

/**
 * Filter issues by severity.
 *
 * @param issues - The issues to filter.
 * @param severity - The severity to filter by.
 * @returns Issues matching the specified severity.
 */
export function filterIssuesBySeverity(
  issues: readonly ValidationIssue[],
  severity: ValidationIssue['severity'],
): ValidationIssue[] {
  return issues.filter((i) => i.severity === severity);
}

/**
 * Filter issues by code.
 *
 * @param issues - The issues to filter.
 * @param code - The issue code to filter by.
 * @returns Issues matching the specified code.
 */
export function filterIssuesByCode(
  issues: readonly ValidationIssue[],
  code: ValidationIssueCode,
): ValidationIssue[] {
  return issues.filter((i) => i.code === code);
}
